name: Keep Alive

on:
  schedule:
    - cron: '*/5 * * * *' # Se ejecuta cada 5 minutos

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Service
        run: curl --silent "https://compresor-q6fh.onrender.com"
